server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            
feign:
  autoconfiguration:
    jackson:
      enabled: true

back-end:
  api-user:
    uri: http://localhost:8081
  api-store:
    uri: http://localhost:8082
  api-product:
    uri: http://localhost:8083